version: "3.7"
services:
    app:
        build:
            args:
                user: oxygem
                uid: 1000
            context: ./
            dockerfile: docker/php.Dockerfile
        image: maprusanovonline-laravel
        container_name: maprusanovonline-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - traffic
    db:
        image: mysql:5.7
        restart: unless-stopped
        container_name: maprusanovonline-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=map.rusanov.online
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        networks:
            - traffic
    nginx:
        image: nginx:alpine
        container_name: maprusanovonline-nginx
        restart: unless-stopped
        build:
            context: .
            dockerfile:
                docker/nginx.Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./logs:/var/log/nginx
        environment:
            - NGINX_HOST=local.map.rusanov.online
            - NGINX_PORT=80
        networks:
            - traffic
networks:
    traffic:
        driver: bridge
